=== kamila-kuhajdova/Kurz_XML_Schema/P11_Unbounded.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- xs:element[name=kurz] -->
<xs:element name="kurz">
 <!-- xs:complexType>xs:sequence -->
<xs:complexType>
	<xs:sequence>
	 <!-- xs:element[name type="xs:string"]*3 -->
	<xs:element name="meno" type="xs:string"></xs:element>
	<xs:element name="lektor" type="xs:string" maxOccurs="unbounded"></xs:element>
	<xs:element name="prerekvizita" type="xs:string" minOccurs="0" maxOccurs="unbounded" ></xs:element>
	</xs:sequence>
</xs:complexType>

</xs:element>

</xs:schema>

=== kamila-kuhajdova/Kurz_XML_Schema/P11_XML_Unbounded.xml
<?xml version="1.0" encoding="UTF-8"?>

<kurz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="P11_Unbounded.xsd">
<!-- meno+lektor+prerekvizita -->
<meno>XML II. XML Schema</meno>
<lektor>Adam Sangala</lektor>
<lektor>Miroslav Reiter</lektor>
<lektor>Mario Kasuba</lektor>
<lektor>Eliska Dlha</lektor>
<prerekvizita>Znalost textoveho editora</prerekvizita>
<prerekvizita>Znalost tabulkoveho editora</prerekvizita>
<prerekvizita>Znalost XML</prerekvizita>
</kurz>
